spring:
    applicaiton:
        name: athena-thirdpart-oss

server:
    port: 9099

oss:
  accessKeyId: L
  endPoint: http://oss-cn-hangzhou.aliyuncs.com
  bucketName: byf-bucket
  accessKeySecret: xd1FQfRMpcnkN2A0DZ8IM41AAyjdpQC

